// =============================================================================
// Agent hooks capability — the backend mechanism that turns the per-agent
// declarations in server/agent-hooks-spec.mjs into a live push event stream.
// Port of Cate 1.5.3 src/runtime/capabilities/agentHooks.ts + agentPresence.ts
// + src/main/ipc/agentSessionStamps.ts (MIT), adapted to CURSEM:
//
//   1. materialize a STABLE per-user hooks dir (~/.cursem/agent-hooks): the
//      stdin→HTTP bridge and per-agent bridge wrappers. Stable on purpose:
//      the bridge paths are embedded in repo-scoped hook files
//      (.claude/settings.local.json, .codex/hooks.json, …), where a per-boot
//      path would rewrite user repos every boot and re-trigger codex's
//      "modified since last trusted" hook review on every restart.
//   2. mint per-terminal hook env (endpoint + HMAC token + CURSEM_TERMINAL_ID)
//      for the TerminalOne env channel;
//   3. prepare workspace-scoped hook files at terminal create time;
//   4. ingest hook posts — NOT on its own listener: the posts ride the
//      existing cursem-server listener via /api/agent-hooks/hook (no new port
//      binds; the machine's port-allocation policy forbids them);
//   5. hook-anchored presence: every authenticated post is made BY the agent
//      (in-process plugins) or by a direct descendant of it (the stdin
//      bridge), so the post itself proves the agent exists and carries a pid
//      that leads to it. A 1 Hz `ps` scan reports liveness of the registered
//      pid; the falling edge resolves 'finished' and clears the resume stamp;
//   6. session stamps ({agentId, sessionId, cwd}) from hook events ONLY —
//      there is deliberately no store-scanning fallback: a guessed stamp
//      risks resuming the WRONG session.
//
// Per Cate 1.5.3, hooks are the ONLY detection channel: an agent that never
// speaks them (codex before its trust prompt is answered, a CLI launched
// before injection) is simply untracked — no PTY-output heuristics anywhere.
// =============================================================================

import { execFile } from 'node:child_process';
import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { chmod, mkdir, readFile, stat, unlink, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import {
  AGENTS,
  AGENT_HOOK_SPECS,
  CURSEM_HOOK_ENDPOINT_ENV,
  CURSEM_HOOK_MARKER,
  CURSEM_HOOK_TOKEN_ENV,
  CURSEM_TERMINAL_ID_ENV,
  agentHookFolder,
  normalizeAgentHookPayload,
  resolveAgentHookMode,
} from './agent-hooks-spec.mjs';

const execFileAsync = promisify(execFile);

export const MAX_HOOK_BODY_BYTES = 512 * 1024;
const PRESENCE_TICK_MS = 1000;

// ---------------------------------------------------------------------------
// Tokens
// ---------------------------------------------------------------------------

/** The bearer token a terminal's hook posts must carry: HMAC-SHA256 of the
 *  terminal id under the per-boot secret. Binding the token to the terminal id
 *  means a process can only post events for ITS OWN terminal — reading the
 *  env of one PTY yields nothing that spoofs another. */
export function hookTokenForTerminal(secret, terminalId) {
  return createHmac('sha256', secret).update(terminalId).digest('hex');
}

/** Constant-time check of the presented bearer against the terminal's derived
 *  token. Length equality first (timingSafeEqual throws on mismatched lengths;
 *  the expected length is public anyway). */
export function hookTokenMatches(authorization, secret, terminalId) {
  if (typeof authorization !== 'string' || !authorization.startsWith('Bearer ')) return false;
  const presented = Buffer.from(authorization.slice('Bearer '.length));
  const expected = Buffer.from(hookTokenForTerminal(secret, terminalId));
  return presented.length === expected.length && timingSafeEqual(presented, expected);
}

/** Whether `cwd` is a place we may plant repo-local hook files: an absolute
 *  path that is NOT the user's home dir (~/.claude, ~/.codex etc. are the
 *  CLIs' USER-GLOBAL config dirs — off-limits) and not empty/relative. */
export function isRepoLocalCwd(cwd, home) {
  return !!cwd && path.isAbsolute(cwd) && !!home && path.resolve(cwd) !== path.resolve(home);
}

async function dirExists(dir) {
  try {
    return (await stat(dir)).isDirectory();
  } catch {
    return false;
  }
}

const shQuote = (s) => `'${s.replace(/'/g, `'\\''`)}'`;

/** The generic stdin→HTTP bridge all stdin-JSON CLIs share (claude, codex,
 *  cursor, grok). No stdout on purpose: every CLI accepts silent exit-0.
 *  Always exits 0 — a hook failure must never surface into the user's agent
 *  turn. */
const BRIDGE_JS = `// Generated by CURSEM IDE (agent hook injection). Do not edit.
'use strict'
const http = require('http')
const agentId = process.argv[2] || ''
let data = ''
process.stdin.setEncoding('utf8')
process.stdin.on('data', (c) => { data += c })
process.stdin.on('end', () => {
  const endpoint = process.env.${CURSEM_HOOK_ENDPOINT_ENV}
  const token = process.env.${CURSEM_HOOK_TOKEN_ENV}
  if (!endpoint || !token || !agentId) process.exit(0)
  // Cross-vendor guard. grok scans OTHER CLIs' hook files (.claude/settings
  // .local.json, .cursor/hooks.json) by default, so a grok session also spawns
  // the wrapper we injected for claude — with a grok payload. GROK_HOOK_EVENT
  // is a RESERVED var grok's hook runner injects into every hook process it
  // spawns (and strips from user-supplied env), so its presence is a
  // deterministic "grok ran me", not a heuristic: drop the post unless the
  // wrapper's baked-in agent id agrees. The grok-native wrapper still reports
  // the event, so nothing is lost.
  if (!!process.env.GROK_HOOK_EVENT !== (agentId === 'grok')) process.exit(0)
  let payload
  try { payload = JSON.parse(data) } catch { payload = { raw: data } }
  // pid: the bridge's PARENT — the agent CLI (or its sh hook-command layer),
  // never the bridge itself. The backend walks the ancestry from here to find
  // the agent process for liveness tracking.
  const body = JSON.stringify({ agentId, terminalId: process.env.${CURSEM_TERMINAL_ID_ENV} || null, pid: process.ppid, payload })
  const req = http.request(endpoint + '/hook', {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: 'Bearer ' + token, 'content-length': Buffer.byteLength(body) },
    timeout: 3000,
  }, (res) => { res.resume(); res.on('end', () => process.exit(0)) })
  req.on('timeout', () => { req.destroy(); process.exit(0) })
  req.on('error', () => process.exit(0))
  req.end(body)
})
// Hard cap so a wedged pipe can never hold the CLI's hook slot open.
setTimeout(() => process.exit(0), 10000)
`;

// ---------------------------------------------------------------------------
// Process table snapshot (`ps` is sufficient on macOS/Linux)
// ---------------------------------------------------------------------------

/** Parse `ps -axo pid=,ppid=,comm=` output into { nameByPid, childrenByPid }.
 *  comm is the full executable path on macOS — basename it so matchers see
 *  'claude', 'grok-4.1', etc. */
export function parseProcessTable(output) {
  const nameByPid = new Map();
  const childrenByPid = new Map();
  for (const line of String(output).split('\n')) {
    const match = line.trim().match(/^(\d+)\s+(\d+)\s+(\S.*)$/);
    if (!match) continue;
    const pid = Number(match[1]);
    const ppid = Number(match[2]);
    const comm = path.basename(match[3].trim());
    nameByPid.set(pid, comm);
    const kids = childrenByPid.get(ppid);
    if (kids) kids.push(pid);
    else childrenByPid.set(ppid, [pid]);
  }
  return { nameByPid, childrenByPid };
}

async function snapshotProcessTable() {
  const { stdout } = await execFileAsync('ps', ['-axo', 'pid=,ppid=,comm='], { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 });
  return parseProcessTable(stdout);
}

function defaultIsAlive(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    // EPERM = alive but not signalable by us; anything else (ESRCH) = gone.
    return error?.code === 'EPERM';
  }
}

/** Invert childrenByPid into child→parent (the walk goes up). */
function parentMap(tree) {
  const parent = new Map();
  for (const [ppid, kids] of tree.childrenByPid) {
    for (const kid of kids) parent.set(kid, ppid);
  }
  return parent;
}

// ---------------------------------------------------------------------------
// Session stamps — resumability gating (port of Cate's agentSessionStamps.ts)
// ---------------------------------------------------------------------------

/**
 * Whether this agent's session is already resumable when its session-start
 * event arrives. claude's SessionStart fires at TUI launch BEFORE any
 * transcript exists, and resuming a transcript-less id FAILS (pinned live by
 * Cate's contract suite) — so claude is only stamped from its first turn
 * event. Everyone else's first sessionId-bearing event is already tied to a
 * persisted store.
 */
const RESUMABLE_FROM_SESSION_START = {
  'claude-code': false,
  codex: true,
  // A never-used sessionStart id is resumable (--resume even ADOPTS unknown
  // ids as a fresh chat rather than failing) — pinned live.
  cursor: true,
  // grok's TUI defers SessionStart to the first prompt submit, so a session is
  // already open and on disk when the id arrives.
  grok: true,
  pi: true,
  opencode: true,
};

// ---------------------------------------------------------------------------
// The capability
// ---------------------------------------------------------------------------

/**
 * deps:
 *   hooksDir      — override the stable hooks dir (tests). Default ~/.cursem/agent-hooks.
 *   originFor()   — the cursem-server loopback origin (http://127.0.0.1:PORT),
 *                   read lazily so the caller can pass a binding that only
 *                   resolves after listen().
 *   stamps        — persistence {get(terminalId), set(stamp), delete(terminalId), list()}
 *                   (server/agent-store.mjs SQLite tables), optional (memory-only).
 *   onEvent(event)                  — normalized AgentHookEvent subscriber.
 *   onPresence(terminalId, present, agentName) — presence edge subscriber.
 *   onStamp(terminalId, stamp|null) — stamp change subscriber.
 *   snapshot()    — process-table snapshot override (tests).
 *   isAlive(pid)  — pid liveness probe override (tests).
 *   home          — home dir override for the repo-local guard (tests).
 *   tickMs        — presence scan interval override (tests).
 */
export function createAgentHooksCapability(deps = {}) {
  const home = deps.home ?? homedir();
  const isAlive = deps.isAlive ?? defaultIsAlive;
  const snapshot = deps.snapshot ?? snapshotProcessTable;
  const tickMs = deps.tickMs ?? PRESENCE_TICK_MS;
  const secret = randomBytes(32).toString('hex');

  let ready = null; // Promise<{dir, contexts}>
  let disposed = false;

  /** terminalId → {agentId, pid, comm} — the hook-anchored registration. */
  const registrations = new Map();
  /** terminalId → {present, agentName} — last emitted presence, for edges. */
  const lastPresence = new Map();
  /** terminalId → cwd reported at pty-env mint time (stamp cwd fallback). */
  const terminalCwds = new Map();
  /** terminalId → stamp dedup key of the last emitted stamp (null = cleared). */
  const stampKeys = new Map();
  let presenceTimer = null;

  const emitEvent = (event) => { try { deps.onEvent?.(event); } catch { /* subscriber must not break ingestion */ } };

  const emitPresence = (terminalId, present, agentName) => {
    const prev = lastPresence.get(terminalId) ?? { present: false, agentName: null };
    if (prev.present === present && prev.agentName === agentName) return;
    lastPresence.set(terminalId, { present, agentName });
    try { deps.onPresence?.(terminalId, present, agentName); } catch { /* ignore */ }
    if (!present && prev.present) clearStamp(terminalId); // falling edge clears the resume stamp
  };

  const emitStamp = (terminalId, stamp) => {
    const key = stamp ? `${stamp.agentId}${stamp.sessionId}${stamp.cwd}` : null;
    if (stampKeys.get(terminalId) === key) return;
    stampKeys.set(terminalId, key);
    if (stamp) {
      try { deps.stamps?.set({ terminalId, ...stamp }); } catch { /* persistence is best-effort */ }
    } else {
      try { deps.stamps?.delete(terminalId); } catch { /* persistence is best-effort */ }
    }
    try { deps.onStamp?.(terminalId, stamp); } catch { /* ignore */ }
  };

  const clearStamp = (terminalId) => emitStamp(terminalId, null);

  // ── Stable hooks dir ────────────────────────────────────────────────────

  /** One-time (lazy) setup: hooks dir + bridge + per-agent wrappers. Lazy so
   *  a server that never spawns a terminal writes nothing. The dir is a
   *  STABLE per-user location (not a per-boot mkdtemp): its bridge paths are
   *  embedded in repo-scoped hook files, and codex keys its persisted hook
   *  trust on them — a churning path would rewrite user repos and re-prompt
   *  "modified since last trusted" on every restart. Contents are still
   *  (re)written on every boot; a partially-built dir left by a failed setup
   *  is harmless and overwritten by the retry. */
  const ensureReady = () => {
    if (ready) return ready;
    ready = buildHooksDir(deps.hooksDir ?? path.join(home, '.cursem', 'agent-hooks'));
    // A failed setup must not wedge every later terminal create on the same
    // rejection — reset so the next create retries.
    ready.catch(() => { ready = null; });
    return ready;
  };

  const buildHooksDir = async (dir) => {
    await mkdir(dir, { recursive: true });
    const bridgeJs = path.join(dir, `${CURSEM_HOOK_MARKER}-bridge.js`);
    await writeFile(bridgeJs, BRIDGE_JS);
    const contexts = new Map();
    for (const agent of AGENTS) {
      // Per-agent bridge wrapper: hook configs get ONE command path with no
      // args (codex runs the command string directly), so the agent id rides
      // as a baked-in argv of the wrapper.
      // NOTE: the wrapper CONTENT embeds this server's node (process.execPath)
      // and is rewritten every boot — two daemons sharing this dir (dev build
      // + packaged app) flip-flop it between their node paths. Benign: both
      // are working node binaries, and codex's hook trust keys on the wrapper
      // PATH (via hooks.json), which never changes.
      const wrapper = path.join(dir, `${CURSEM_HOOK_MARKER}-bridge-${agent.id}${process.platform === 'win32' ? '.cmd' : ''}`);
      if (process.platform === 'win32') {
        await writeFile(wrapper, `@echo off\r\n"${process.execPath}" "${bridgeJs}" "${agent.id}" %*\r\n`);
      } else {
        await writeFile(wrapper, `#!/bin/sh\nexec ${shQuote(process.execPath)} ${shQuote(bridgeJs)} ${shQuote(agent.id)} "$@"\n`);
        await chmod(wrapper, 0o755);
      }
      contexts.set(agent.id, { bridgeCommand: wrapper });
    }
    return { dir, contexts };
  };

  // ── Presence ─────────────────────────────────────────────────────────────

  /** Ingest one authenticated hook post's lineage claim. Resolves (and
   *  re-resolves after an agent relaunch) the registered agent pid for the
   *  terminal. Awaited before answering the post — the bridge's ancestry
   *  chain is only guaranteed alive while the post is in flight. */
  const notePost = async (terminalId, agentId, pid) => {
    // Reject anything that isn't a plain positive pid: posts are made by
    // processes inside the terminal, so the value is untrusted input (and
    // pid 0 / negatives address process GROUPS in kill()).
    if (pid === undefined || !Number.isInteger(pid) || pid <= 0) return;
    const def = AGENTS.find((a) => a.id === agentId);
    if (!def) return;

    // Fast path: this terminal's agent is already registered and alive —
    // the common per-tool-call event needs no snapshot.
    const existing = registrations.get(terminalId);
    if (existing && existing.agentId === agentId && isAlive(existing.pid)) {
      emitPresence(terminalId, true, def.displayName);
      return;
    }

    const tree = await snapshot();
    const parent = parentMap(tree);
    const visited = new Set();
    // Inclusive walk: an in-process plugin posts the agent's own pid; the
    // bridge posts its parent (possibly with sh/npm layers above it).
    for (let p = pid; p !== undefined && !visited.has(p); p = parent.get(p)) {
      visited.add(p);
      const comm = tree.nameByPid.get(p);
      if (comm && def.matchProcess(comm.toLowerCase())) {
        registrations.set(terminalId, { agentId, pid: p, comm });
        emitPresence(terminalId, true, def.displayName);
        return;
      }
    }
    // No matching ancestor (matcher miss, or the chain died before the
    // snapshot): leave nothing registered — a wrong pid (a shell, a tmux
    // server) would never fall, which is worse than reading absent.
  };

  /** 1 Hz liveness scan over registered terminals: a registered pid that
   *  vanished — or changed comm (pid reuse) — reads absent: the falling edge. */
  const scanTick = async () => {
    if (registrations.size === 0) return;
    let tree;
    try {
      tree = await snapshot();
    } catch {
      return; // a failed scan must not kill live registrations
    }
    for (const [terminalId, reg] of Array.from(registrations.entries())) {
      if (tree.nameByPid.get(reg.pid) === reg.comm) continue;
      registrations.delete(terminalId);
      emitPresence(terminalId, false, null);
    }
  };

  const ensurePresenceLoop = () => {
    if (presenceTimer || disposed) return;
    presenceTimer = setInterval(() => { void scanTick(); }, tickMs);
    presenceTimer.unref?.();
  };

  // ── Session stamps ───────────────────────────────────────────────────────

  /** Ingest one normalized hook event and update the terminal's resume stamp:
   *  session-end clears it; any other sessionId-bearing event stamps, except
   *  a session-start for an agent whose sessions aren't resumable yet at that
   *  point (claude). cwd comes from the event when the payload carries one,
   *  else from the terminal's cwd recorded at pty-env mint time. */
  const ingestStamp = (event) => {
    const { terminalId } = event;
    if (event.kind === 'session-end') {
      clearStamp(terminalId);
      return;
    }
    if (event.sessionId == null) return;
    if (event.kind === 'session-start' && !RESUMABLE_FROM_SESSION_START[event.agentId]) return;
    emitStamp(terminalId, {
      agentId: event.agentId,
      sessionId: event.sessionId,
      cwd: event.cwd ?? terminalCwds.get(terminalId) ?? '',
    });
  };

  // ── Workspace injection ──────────────────────────────────────────────────

  /** Write (or, for 'off', remove) workspace-scoped hook files for the
   *  terminal's cwd and keep the ones we wrote out of git status via
   *  .git/info/exclude. Best-effort and idempotent; never touches the
   *  user's home dir. */
  const prepareWorkspace = async (cwd, config) => {
    if (disposed) return;
    if (!isRepoLocalCwd(cwd, home)) return;
    let state;
    try {
      state = await ensureReady();
    } catch {
      return;
    }
    const excludeRels = [];
    for (const agent of AGENTS) {
      const spec = AGENT_HOOK_SPECS[agent.id];
      if (!spec.projectFiles) continue;
      const mode = resolveAgentHookMode(config, agent.id);
      // 'off': reclaim anything we previously injected, then move on.
      if (mode === 'off') {
        for (const pf of spec.projectFiles) {
          const filePath = path.join(cwd, pf.relPath);
          let existing;
          try {
            existing = await readFile(filePath, 'utf-8');
          } catch { continue; /* absent — nothing to strip */ }
          try {
            const res = pf.strip?.(existing);
            if (res && 'delete' in res) await unlink(filePath);
            else if (res && 'content' in res && res.content !== existing) await writeFile(filePath, res.content);
          } catch { /* best-effort — never block the terminal spawn */ }
        }
        continue;
      }
      // 'auto': inject only when the agent's config folder is already in the
      // repo (a "used here" signal). 'on': always inject.
      if (mode === 'auto') {
        const folder = agentHookFolder(agent.id);
        if (folder && !(await dirExists(path.join(cwd, folder)))) continue;
      }
      const ctx = state.contexts.get(agent.id);
      for (const pf of spec.projectFiles) {
        const filePath = path.join(cwd, pf.relPath);
        let existing = null;
        try {
          existing = await readFile(filePath, 'utf-8');
        } catch { /* absent */ }
        let wrote = false;
        try {
          const next = pf.build(existing, ctx);
          if (next !== null) {
            await mkdir(path.dirname(filePath), { recursive: true });
            await writeFile(filePath, next);
            wrote = true;
          }
        } catch { /* best-effort — never block the terminal spawn */ }
        // Keep OUR file out of git status; a purely-user file we left alone
        // is not ours to hide.
        if (wrote || existing?.includes(CURSEM_HOOK_MARKER)) excludeRels.push(pf.relPath);
      }
    }
    if (excludeRels.length > 0) await ensureGitExcluded(cwd, excludeRels);
  };

  // ── Public surface ───────────────────────────────────────────────────────

  return {
    /** The hook env for one PTY (endpoint + this terminal's derived token +
     *  CURSEM_TERMINAL_ID), or null when hook setup is unavailable (a plain
     *  shell is always spawnable). Agent-agnostic and repo-free, so it is
     *  minted unconditionally. */
    async envForPty(terminalId, cwd, config) {
      if (disposed) return null;
      const origin = typeof deps.originFor === 'function' ? deps.originFor() : deps.originFor;
      if (!origin) return null;
      let state;
      try {
        state = await ensureReady();
      } catch {
        return null;
      }
      terminalCwds.set(terminalId, cwd ?? '');
      ensurePresenceLoop();
      // Per-spawn, idempotent, best-effort — the same semantics as Cate's
      // PTY-create hook. Never block the terminal spawn on a write failure.
      if (cwd) {
        try { await prepareWorkspace(cwd, config); } catch { /* best-effort */ }
      }
      return {
        endpoint: `${origin}/api/agent-hooks`,
        bridgeDir: state.dir,
        terminalEnv: {
          [CURSEM_HOOK_ENDPOINT_ENV]: `${origin}/api/agent-hooks`,
          [CURSEM_HOOK_TOKEN_ENV]: hookTokenForTerminal(secret, terminalId),
          [CURSEM_TERMINAL_ID_ENV]: terminalId,
        },
      };
    },

    prepareWorkspace,

    /** Inspect a workspace's per-agent hook-file injection state (for the
     *  Settings UI). Read-only. */
    async inspectWorkspace(cwd) {
      const repoLocal = isRepoLocalCwd(cwd, home);
      const states = [];
      for (const agent of AGENTS) {
        const spec = AGENT_HOOK_SPECS[agent.id];
        let folderPresent = false;
        let injected = false;
        if (repoLocal) {
          const folder = agentHookFolder(agent.id);
          folderPresent = folder ? await dirExists(path.join(cwd, folder)) : false;
          for (const pf of spec.projectFiles ?? []) {
            try {
              const content = await readFile(path.join(cwd, pf.relPath), 'utf-8');
              if (content.includes(CURSEM_HOOK_MARKER)) {
                injected = true;
                break;
              }
            } catch { /* absent — not injected via this path */ }
          }
        }
        states.push({ agentId: agent.id, displayName: agent.displayName, folderPresent, injected });
      }
      return states;
    },

    /** Ingest one hook post. Returns an HTTP-ish status: 204 accepted (also
     *  for unknown agents / untracked events — the post is authenticated),
     *  401 bad token, 400 malformed. Awaits the presence walk BEFORE
     *  answering so the bridge's ancestry chain stays alive through it. */
    async handleHookPost(body, authorization) {
      if (
        typeof body?.agentId !== 'string'
        || typeof body?.terminalId !== 'string'
        || !body.terminalId
        || typeof body?.payload !== 'object'
        || body.payload === null
      ) return { status: 400 };
      // The token is PER TERMINAL (HMAC of the claimed terminalId), so it can
      // only be validated after the body names the terminal. A forged
      // terminalId fails here: its token lives only in that pty's env.
      if (!hookTokenMatches(authorization, secret, body.terminalId)) return { status: 401 };
      // Presence lineage: every authenticated post from a known agent counts,
      // even one whose payload normalizes to null — the post itself proves
      // the agent is alive.
      if (body.agentId in AGENT_HOOK_SPECS) {
        try {
          await notePost(body.terminalId, body.agentId, typeof body.pid === 'number' ? body.pid : undefined);
        } catch { /* presence tracking must never fail the hook */ }
      }
      const event = normalizeAgentHookPayload(body.agentId, body.terminalId, body.payload);
      if (event) {
        ingestStamp(event);
        emitEvent(event);
      }
      return { status: 204, event };
    },

    /** All persisted stamps (frontend boot hydration). */
    listStamps() {
      try {
        return deps.stamps?.list() ?? [];
      } catch {
        return [];
      }
    },

    /** One-shot claim for terminal resurrection: returns and DELETES the
     *  newest stamp, preferring one whose cwd matches. Never returns the same
     *  stamp twice — a claimed stamp is consumed even if the resume fails. */
    claimStamp(cwd) {
      let stamps;
      try {
        stamps = deps.stamps?.list() ?? [];
      } catch {
        return null;
      }
      if (stamps.length === 0) return null;
      const stamp = stamps.find((s) => cwd && s.cwd === cwd) ?? stamps[0];
      try { deps.stamps?.delete(stamp.terminalId); } catch { /* best-effort */ }
      stampKeys.set(stamp.terminalId, null);
      return stamp;
    },

    /** Snapshot of current presence (SSE connect hydration). */
    presenceSnapshot() {
      return Array.from(lastPresence.entries()).map(([terminalId, value]) => ({ terminalId, ...value }));
    },

    /** Test/diagnostic handle. */
    tokenFor: (terminalId) => hookTokenForTerminal(secret, terminalId),
    notePost,
    scanTick,
    registrations,

    dispose() {
      disposed = true;
      if (presenceTimer) {
        clearInterval(presenceTimer);
        presenceTimer = null;
      }
      // The stable hooks dir is deliberately NOT removed: repo hook files
      // embed its bridge paths, which must stay valid across restarts.
    },
  };
}

/**
 * Add `/<rel>` anchors for the hook files to the repo's .git/info/exclude
 * (NEVER .gitignore — user repos stay byte-identical). Handles worktrees: a
 * `.git` FILE points at .git/worktrees/<name>, whose `commondir` locates the
 * shared git dir where info/exclude lives. Best-effort throughout — on any
 * failure the hook files merely show up as untracked.
 */
export async function ensureGitExcluded(cwd, relPaths) {
  try {
    // Find the enclosing repo root (the dir holding `.git`).
    let repoRoot = null;
    let dotGit = null;
    for (let dir = cwd; ; dir = path.dirname(dir)) {
      const candidate = path.join(dir, '.git');
      try {
        await stat(candidate);
        repoRoot = dir;
        dotGit = candidate;
        break;
      } catch { /* keep walking up */ }
      if (dir === path.dirname(dir)) return; // hit fs root — not a repo
    }
    // Resolve the git dir: a directory, or a worktree's `gitdir:` pointer file
    // (then its commondir for the shared info/ dir).
    let gitDir = dotGit;
    if ((await stat(dotGit)).isFile()) {
      const m = (await readFile(dotGit, 'utf-8')).match(/^gitdir:\s*(.+)\s*$/m);
      if (!m) return;
      gitDir = path.resolve(repoRoot, m[1].trim());
    }
    try {
      const common = (await readFile(path.join(gitDir, 'commondir'), 'utf-8')).trim();
      gitDir = path.resolve(gitDir, common);
    } catch { /* no commondir — gitDir IS the common dir */ }

    const excludePath = path.join(gitDir, 'info', 'exclude');
    let existing = '';
    try {
      existing = await readFile(excludePath, 'utf-8');
    } catch { /* absent — created below */ }
    const lines = relPaths
      .map((rel) => '/' + path.relative(repoRoot, path.join(cwd, rel)).split(path.sep).join('/'))
      .filter((line) => !line.startsWith('/..')) // cwd outside the repo — never write a bogus anchor
      .filter((line) => !existing.split('\n').includes(line));
    if (lines.length === 0) return;
    await mkdir(path.dirname(excludePath), { recursive: true });
    const sep = existing.length === 0 || existing.endsWith('\n') ? '' : '\n';
    await writeFile(excludePath, existing + sep + lines.join('\n') + '\n');
  } catch { /* best-effort */ }
}
