// Ported from Cate 1.5.3 (MIT) unified themes — generated by a one-off
// conversion script. Chrome keys are mapped onto CURSEM semantic tokens
// (surface-0..5 → bg.*, text-* → fg.*, focus-blue → accent, activity/git
// status → semantic.*); terminal palettes and Monaco token rules are carried
// verbatim, which is where each theme's 16-ANSI identity lives.
import { makeTheme } from './makeTheme';
import type { TerminalPalette, ThemeEditorDefinition } from './types';

export const CATE_THEMES = [
  makeTheme({
    "id": "dark-cold",
    "name": "Dark Cold",
    "group": "Cate collection",
    "description": "Cate’s default dark: neutral slate surfaces with a crisp blue focus.",
    "mode": "dark",
    "colors": {
      "canvas": "#18181a",
      "editor": "#1f1f22",
      "surface": "#24242a",
      "raised": "#2a2a30",
      "hover": "#2f2f35",
      "active": "#35353c",
      "border": "rgba(235, 235, 245, 0.06)",
      "borderStrong": "rgba(235, 235, 245, 0.12)",
      "text": "#f2f2f7",
      "secondary": "#8e8e93",
      "muted": "#727276",
      "accent": "#0a84ff",
      "companion": "#64d2ff",
      "success": "#30d158",
      "warning": "#ff9f0a",
      "error": "#ff453a",
      "comment": "#727276",
      "keyword": "#0a84ff",
      "string": "#30d158",
      "number": "#ff9f0a",
      "function": "#0a84ff",
      "type": "#64d2ff",
      "operator": "#8e8e93"
    },
    "terminal": {
      "background": "#1c1c1e",
      "foreground": "#f2f2f7",
      "cursor": "#0a84ff",
      "selectionBackground": "rgba(10, 132, 255, 0.28)",
      "selectionForeground": "#f2f2f7",
      "black": "#1c1c1e",
      "red": "#ff453a",
      "green": "#30d158",
      "yellow": "#ffd60a",
      "blue": "#0a84ff",
      "magenta": "#bf5af2",
      "cyan": "#64d2ff",
      "white": "#d1d1d6",
      "brightBlack": "#6b6b6e",
      "brightRed": "#ff6961",
      "brightGreen": "#5de36e",
      "brightYellow": "#ffe066",
      "brightBlue": "#5eb0ff",
      "brightMagenta": "#d28cf6",
      "brightCyan": "#8ee0ff",
      "brightWhite": "#f2f2f7"
    },
    "editor": {
      "base": "vs-dark",
      "colors": {
        "editor.background": "#1e1e1e",
        "editorGutter.background": "#1e1e1e",
        "minimap.background": "#1e1e1e",
        "editor.lineHighlightBorder": "#00000000",
        "contrastBorder": "#00000000"
      },
      "tokens": []
    },
    "bootBackground": "#1a1d22"
  }),
  makeTheme({
    "id": "dark-warm",
    "name": "Dark Warm",
    "group": "Cate collection",
    "description": "Warm umber surfaces and a calm blue focus, ported from Cate.",
    "mode": "dark",
    "colors": {
      "canvas": "#1d1c1a",
      "editor": "#232220",
      "surface": "#282724",
      "raised": "#2c2b28",
      "hover": "#322f2c",
      "active": "#3a3733",
      "border": "rgba(255, 255, 255, 0.035)",
      "borderStrong": "rgba(255, 255, 255, 0.14)",
      "text": "#e8e6e3",
      "secondary": "#a8a49e",
      "muted": "#78746e",
      "accent": "#4a9eff",
      "companion": "#11A8CD",
      "success": "#4dd964",
      "warning": "#ff9f0a",
      "error": "#ff453a",
      "comment": "#78746e",
      "keyword": "#4a9eff",
      "string": "#4dd964",
      "number": "#ff9f0a",
      "function": "#4a9eff",
      "type": "#11A8CD",
      "operator": "#a8a49e"
    },
    "terminal": {
      "background": "#1f1e1c",
      "foreground": "#D4D4D4",
      "cursor": "#AEAFAD",
      "selectionBackground": "#264F78",
      "selectionForeground": "#D4D4D4",
      "black": "#000000",
      "red": "#CD3131",
      "green": "#0DBC79",
      "yellow": "#E5E510",
      "blue": "#2472C8",
      "magenta": "#BC3FBC",
      "cyan": "#11A8CD",
      "white": "#E5E5E5",
      "brightBlack": "#6e6e6e",
      "brightRed": "#F14C4C",
      "brightGreen": "#23D18B",
      "brightYellow": "#F5F543",
      "brightBlue": "#3B8EEA",
      "brightMagenta": "#D670D6",
      "brightCyan": "#29B8DB",
      "brightWhite": "#FFFFFF"
    },
    "editor": {
      "base": "vs-dark",
      "colors": {
        "editor.background": "#1f1e1c",
        "editorGutter.background": "#1f1e1c",
        "minimap.background": "#1f1e1c",
        "editor.lineHighlightBorder": "#00000000",
        "contrastBorder": "#00000000"
      },
      "tokens": []
    },
    "bootBackground": "#1f1e1c"
  }),
  makeTheme({
    "id": "dark-neutral",
    "name": "Dark Neutral",
    "group": "Cate collection",
    "description": "Zero-tint neutral grays for distraction-free work.",
    "mode": "dark",
    "colors": {
      "canvas": "#191919",
      "editor": "#1e1e1e",
      "surface": "#262626",
      "raised": "#2c2c2c",
      "hover": "#323232",
      "active": "#383838",
      "border": "rgba(255, 255, 255, 0.10)",
      "borderStrong": "rgba(255, 255, 255, 0.18)",
      "text": "#e6e6e6",
      "secondary": "#a0a0a0",
      "muted": "#757575",
      "accent": "#5e86c3",
      "companion": "#6fb0b0",
      "success": "#5cae72",
      "warning": "#cc8a4a",
      "error": "#d16a6a",
      "comment": "#757575",
      "keyword": "#5e86c3",
      "string": "#5cae72",
      "number": "#cc8a4a",
      "function": "#5e86c3",
      "type": "#6fb0b0",
      "operator": "#a0a0a0"
    },
    "terminal": {
      "background": "#1a1a1a",
      "foreground": "#e6e6e6",
      "cursor": "#5e86c3",
      "selectionBackground": "rgba(94, 134, 195, 0.26)",
      "selectionForeground": "#f2f2f2",
      "black": "#1a1a1a",
      "red": "#d17a72",
      "green": "#8bb072",
      "yellow": "#d0a95f",
      "blue": "#6f95c6",
      "magenta": "#b585c0",
      "cyan": "#6fb0b0",
      "white": "#cccccc",
      "brightBlack": "#6e6e6e",
      "brightRed": "#e0928a",
      "brightGreen": "#a4c48c",
      "brightYellow": "#e0bd7c",
      "brightBlue": "#8aabd8",
      "brightMagenta": "#c89fd0",
      "brightCyan": "#8cc4c4",
      "brightWhite": "#f2f2f2"
    },
    "editor": {
      "base": "vs-dark",
      "colors": {
        "editor.background": "#1c1c1c",
        "editorGutter.background": "#1c1c1c",
        "minimap.background": "#1c1c1c",
        "editor.lineHighlightBorder": "#00000000",
        "contrastBorder": "#00000000"
      },
      "tokens": []
    },
    "bootBackground": "#191919"
  }),
  makeTheme({
    "id": "clay-dark",
    "name": "Clay Dark",
    "group": "Cate collection",
    "description": "Earthy clay tones with terracotta warmth.",
    "mode": "dark",
    "colors": {
      "canvas": "#161513",
      "editor": "#1e1c1a",
      "surface": "#262421",
      "raised": "#2e2c28",
      "hover": "#37342f",
      "active": "#413e3a",
      "border": "rgba(236, 230, 218, 0.07)",
      "borderStrong": "rgba(236, 230, 218, 0.14)",
      "text": "#ece6da",
      "secondary": "#c8c6bc",
      "muted": "#a4a298",
      "accent": "#d88764",
      "companion": "#6fb3a8",
      "success": "#9eb07c",
      "warning": "#d4a45f",
      "error": "#cf8d8d",
      "comment": "#847c70",
      "keyword": "#cf8d8d",
      "string": "#9eb07c",
      "number": "#d4a45f",
      "function": "#7fa3c4",
      "type": "#6fb3a8",
      "operator": "#b3a18e"
    },
    "terminal": {
      "background": "#161513",
      "foreground": "#ece6da",
      "cursor": "#d88764",
      "cursorAccent": "#161513",
      "selectionBackground": "#332d27",
      "black": "#1e1c1a",
      "red": "#cf8d8d",
      "green": "#9eb07c",
      "yellow": "#d4a45f",
      "blue": "#7fa3c4",
      "magenta": "#c2a0c2",
      "cyan": "#6fb3a8",
      "white": "#d8d2c6",
      "brightBlack": "#6f685e",
      "brightRed": "#dba3a3",
      "brightGreen": "#b2c194",
      "brightYellow": "#e2b97a",
      "brightBlue": "#99b6d4",
      "brightMagenta": "#d2b6d2",
      "brightCyan": "#8cc7bd",
      "brightWhite": "#f4eee3"
    },
    "editor": {
      "base": "vs-dark",
      "colors": {
        "editor.background": "#161513",
        "editor.foreground": "#ece6da",
        "editorGutter.background": "#161513",
        "minimap.background": "#161513",
        "editorLineNumber.foreground": "#6f685e",
        "editorLineNumber.activeForeground": "#a4a298",
        "editor.selectionBackground": "#332d27",
        "editor.lineHighlightBackground": "#1e1c1a",
        "editorCursor.foreground": "#d88764",
        "editorIndentGuide.background1": "#2e2c28",
        "editorWhitespace.foreground": "#2e2c28"
      },
      "tokens": [
        {
          "token": "comment",
          "foreground": "847c70",
          "fontStyle": "italic"
        },
        {
          "token": "keyword",
          "foreground": "cf8d8d"
        },
        {
          "token": "storage",
          "foreground": "cf8d8d"
        },
        {
          "token": "keyword.control",
          "foreground": "cf8d8d"
        },
        {
          "token": "string",
          "foreground": "9eb07c"
        },
        {
          "token": "constant.numeric",
          "foreground": "d4a45f"
        },
        {
          "token": "constant.language",
          "foreground": "d4a45f"
        },
        {
          "token": "variable",
          "foreground": "ddd6c9"
        },
        {
          "token": "variable.parameter",
          "foreground": "ddd6c9"
        },
        {
          "token": "entity.name.function",
          "foreground": "7fa3c4"
        },
        {
          "token": "support.function",
          "foreground": "7fa3c4"
        },
        {
          "token": "type",
          "foreground": "6fb3a8"
        },
        {
          "token": "entity.name.type",
          "foreground": "6fb3a8"
        },
        {
          "token": "entity.name.class",
          "foreground": "6fb3a8"
        },
        {
          "token": "entity.name.tag",
          "foreground": "d88764"
        },
        {
          "token": "entity.other.attribute-name",
          "foreground": "d4a45f"
        },
        {
          "token": "regexp",
          "foreground": "6fb3a8"
        },
        {
          "token": "operator",
          "foreground": "b3a18e"
        },
        {
          "token": "punctuation",
          "foreground": "b3a18e"
        },
        {
          "token": "invalid",
          "foreground": "dba3a3"
        }
      ]
    },
    "bootBackground": "#161513"
  }),
  makeTheme({
    "id": "one-dark-pro",
    "name": "One Dark Pro",
    "group": "Popular dark terminals",
    "description": "The classic One Dark Pro palette from Atom/VS Code.",
    "mode": "dark",
    "colors": {
      "canvas": "#282c34",
      "editor": "#21252b",
      "surface": "#2c313a",
      "raised": "#333842",
      "hover": "#3a3f4b",
      "active": "#404654",
      "border": "#1b1d23",
      "borderStrong": "#404553",
      "text": "#abb2bf",
      "secondary": "#9da5b4",
      "muted": "#767e8e",
      "accent": "#61afef",
      "companion": "#56b6c2",
      "success": "#98c379",
      "warning": "#d19a66",
      "error": "#e06c75",
      "comment": "#7f848e",
      "keyword": "#c678dd",
      "string": "#98c379",
      "number": "#d19a66",
      "function": "#61afef",
      "type": "#e5c07b",
      "operator": "#56b6c2"
    },
    "terminal": {
      "background": "#282c34",
      "foreground": "#abb2bf",
      "cursor": "#528bff",
      "selectionBackground": "#3e4451",
      "black": "#3f4451",
      "red": "#e06c75",
      "green": "#98c379",
      "yellow": "#d19a66",
      "blue": "#61afef",
      "magenta": "#c678dd",
      "cyan": "#56b6c2",
      "white": "#abb2bf",
      "brightBlack": "#717989",
      "brightRed": "#e06c75",
      "brightGreen": "#98c379",
      "brightYellow": "#e5c07b",
      "brightBlue": "#61afef",
      "brightMagenta": "#c678dd",
      "brightCyan": "#56b6c2",
      "brightWhite": "#ffffff"
    },
    "editor": {
      "base": "vs-dark",
      "colors": {
        "editor.background": "#282c34",
        "editor.foreground": "#abb2bf",
        "editor.selectionBackground": "#3e4451",
        "editor.lineHighlightBackground": "#2c313c",
        "editorCursor.foreground": "#528bff",
        "editorLineNumber.foreground": "#495162",
        "editorLineNumber.activeForeground": "#abb2bf"
      },
      "tokens": [
        {
          "token": "comment",
          "foreground": "7f848e",
          "fontStyle": "italic"
        },
        {
          "token": "keyword",
          "foreground": "c678dd"
        },
        {
          "token": "keyword.control",
          "foreground": "c678dd"
        },
        {
          "token": "storage",
          "foreground": "c678dd"
        },
        {
          "token": "storage.type",
          "foreground": "c678dd"
        },
        {
          "token": "string",
          "foreground": "98c379"
        },
        {
          "token": "constant.numeric",
          "foreground": "d19a66"
        },
        {
          "token": "constant.language",
          "foreground": "d19a66"
        },
        {
          "token": "constant",
          "foreground": "56b6c2"
        },
        {
          "token": "variable",
          "foreground": "e06c75"
        },
        {
          "token": "variable.parameter",
          "foreground": "abb2bf"
        },
        {
          "token": "type",
          "foreground": "e5c07b"
        },
        {
          "token": "entity.name.type",
          "foreground": "e5c07b"
        },
        {
          "token": "entity.name.class",
          "foreground": "e5c07b"
        },
        {
          "token": "entity.name.function",
          "foreground": "61afef"
        },
        {
          "token": "support.function",
          "foreground": "61afef"
        },
        {
          "token": "entity.name.tag",
          "foreground": "e06c75"
        },
        {
          "token": "entity.other.attribute-name",
          "foreground": "d19a66"
        },
        {
          "token": "operator",
          "foreground": "56b6c2"
        }
      ]
    },
    "bootBackground": "#282c34"
  }),
  makeTheme({
    "id": "visual-studio-dark",
    "name": "Visual Studio Dark",
    "group": "Popular dark terminals",
    "description": "Visual Studio’s familiar dark editor palette.",
    "mode": "dark",
    "colors": {
      "canvas": "#1e1e1e",
      "editor": "#252526",
      "surface": "#2d2d2d",
      "raised": "#333333",
      "hover": "#3c3c3c",
      "active": "#424242",
      "border": "#2b2b2b",
      "borderStrong": "#454545",
      "text": "#d4d4d4",
      "secondary": "#cccccc",
      "muted": "#858585",
      "accent": "#007acc",
      "companion": "#11a8cd",
      "success": "#4ec9b0",
      "warning": "#ce9178",
      "error": "#f48771",
      "comment": "#6a9955",
      "keyword": "#569cd6",
      "string": "#ce9178",
      "number": "#b5cea8",
      "function": "#dcdcaa",
      "type": "#4ec9b0",
      "operator": "#d4d4d4"
    },
    "terminal": {
      "background": "#1e1e1e",
      "foreground": "#cccccc",
      "cursor": "#d4d4d4",
      "selectionBackground": "#264f78",
      "black": "#000000",
      "red": "#cd3131",
      "green": "#0dbc79",
      "yellow": "#e5e510",
      "blue": "#2472c8",
      "magenta": "#bc3fbc",
      "cyan": "#11a8cd",
      "white": "#e5e5e5",
      "brightBlack": "#6e6e6e",
      "brightRed": "#f14c4c",
      "brightGreen": "#23d18b",
      "brightYellow": "#f5f543",
      "brightBlue": "#3b8eea",
      "brightMagenta": "#d670d6",
      "brightCyan": "#29b8db",
      "brightWhite": "#ffffff"
    },
    "editor": {
      "base": "vs-dark",
      "colors": {
        "editor.background": "#1e1e1e",
        "editor.foreground": "#d4d4d4",
        "editor.selectionBackground": "#264f78",
        "editor.lineHighlightBackground": "#2a2a2a",
        "editorCursor.foreground": "#aeafad",
        "editorLineNumber.foreground": "#858585",
        "editorLineNumber.activeForeground": "#c6c6c6"
      },
      "tokens": [
        {
          "token": "comment",
          "foreground": "6a9955",
          "fontStyle": "italic"
        },
        {
          "token": "keyword",
          "foreground": "569cd6"
        },
        {
          "token": "keyword.control",
          "foreground": "c586c0"
        },
        {
          "token": "storage",
          "foreground": "569cd6"
        },
        {
          "token": "storage.type",
          "foreground": "569cd6"
        },
        {
          "token": "string",
          "foreground": "ce9178"
        },
        {
          "token": "constant.numeric",
          "foreground": "b5cea8"
        },
        {
          "token": "constant.language",
          "foreground": "569cd6"
        },
        {
          "token": "constant",
          "foreground": "4fc1ff"
        },
        {
          "token": "variable",
          "foreground": "9cdcfe"
        },
        {
          "token": "variable.parameter",
          "foreground": "9cdcfe"
        },
        {
          "token": "type",
          "foreground": "4ec9b0"
        },
        {
          "token": "entity.name.type",
          "foreground": "4ec9b0"
        },
        {
          "token": "entity.name.class",
          "foreground": "4ec9b0"
        },
        {
          "token": "entity.name.function",
          "foreground": "dcdcaa"
        },
        {
          "token": "support.function",
          "foreground": "dcdcaa"
        },
        {
          "token": "entity.name.tag",
          "foreground": "569cd6"
        },
        {
          "token": "entity.other.attribute-name",
          "foreground": "9cdcfe"
        },
        {
          "token": "operator",
          "foreground": "d4d4d4"
        }
      ]
    },
    "bootBackground": "#1e1e1e"
  }),
  makeTheme({
    "id": "light-subtle",
    "name": "Light Subtle",
    "group": "Light themes",
    "description": "Cate’s default light: warm parchment surfaces, blue focus.",
    "mode": "light",
    "colors": {
      "canvas": "#b1a696",
      "editor": "#bdb3a3",
      "surface": "#c8bfb0",
      "raised": "#c3b9a9",
      "hover": "#beb4a4",
      "active": "#b8ae9e",
      "border": "rgba(56, 50, 43, 0.10)",
      "borderStrong": "rgba(56, 50, 43, 0.20)",
      "text": "#1a1612",
      "secondary": "#38322b",
      "muted": "#5e574c",
      "accent": "#1a59c6",
      "companion": "#5e747f",
      "success": "#4a8f3a",
      "warning": "#cb4b16",
      "error": "#b72927",
      "comment": "#5e574c",
      "keyword": "#206bee",
      "string": "#4a8f3a",
      "number": "#cb4b16",
      "function": "#206bee",
      "type": "#5e747f",
      "operator": "#38322b"
    },
    "terminal": {
      "background": "#ddd5ca",
      "foreground": "#38322b",
      "cursor": "#3c7ef0",
      "cursorAccent": "#ddd5ca",
      "selectionBackground": "#b1a696",
      "selectionForeground": "#38322b",
      "black": "#38322b",
      "red": "#c04030",
      "green": "#428034",
      "yellow": "#916e00",
      "blue": "#246eee",
      "magenta": "#a04a7a",
      "cyan": "#5e747f",
      "white": "#797266",
      "brightBlack": "#5e747f",
      "brightRed": "#cb4b16",
      "brightGreen": "#5fa34a",
      "brightYellow": "#c89a1f",
      "brightBlue": "#256df0",
      "brightMagenta": "#b85a8a",
      "brightCyan": "#7a8f99",
      "brightWhite": "#38322b"
    },
    "editor": {
      "base": "vs",
      "colors": {
        "editor.background": "#ddd5ca",
        "editorGutter.background": "#ddd5ca",
        "minimap.background": "#ddd5ca",
        "editor.foreground": "#38322b",
        "editorLineNumber.foreground": "#8a8274",
        "editorLineNumber.activeForeground": "#38322b",
        "editor.lineHighlightBackground": "#e5dfd6",
        "editor.lineHighlightBorder": "#00000000",
        "editor.selectionBackground": "#c8bfb0",
        "editorCursor.foreground": "#3c7ef0",
        "contrastBorder": "#00000000"
      },
      "tokens": []
    },
    "bootBackground": "#f4f3f0"
  }),
  makeTheme({
    "id": "one-light",
    "name": "One Light",
    "group": "Light themes",
    "description": "Atom One Light’s clean daylight syntax palette.",
    "mode": "light",
    "colors": {
      "canvas": "#fafafa",
      "editor": "#f0f0f1",
      "surface": "#eaeaeb",
      "raised": "#e5e5e6",
      "hover": "#dbdbdc",
      "active": "#d0d0d1",
      "border": "#e1e1e2",
      "borderStrong": "#c9c9ca",
      "text": "#383a42",
      "secondary": "#4f525e",
      "muted": "#80828a",
      "accent": "#4078f2",
      "companion": "#0184bc",
      "success": "#50a14f",
      "warning": "#c18401",
      "error": "#e45649",
      "comment": "#a0a1a7",
      "keyword": "#a626a4",
      "string": "#50a14f",
      "number": "#986801",
      "function": "#4078f2",
      "type": "#c18401",
      "operator": "#0184bc"
    },
    "terminal": {
      "background": "#fafafa",
      "foreground": "#383a42",
      "cursor": "#526fff",
      "selectionBackground": "#dbdbdc",
      "black": "#383a42",
      "red": "#e45649",
      "green": "#50a14f",
      "yellow": "#c18401",
      "blue": "#4078f2",
      "magenta": "#a626a4",
      "cyan": "#0184bc",
      "white": "#8b8c93",
      "brightBlack": "#696c77",
      "brightRed": "#e45649",
      "brightGreen": "#50a14f",
      "brightYellow": "#986801",
      "brightBlue": "#4078f2",
      "brightMagenta": "#a626a4",
      "brightCyan": "#0184bc",
      "brightWhite": "#2c2e36"
    },
    "editor": {
      "base": "vs",
      "colors": {
        "editor.background": "#fafafa",
        "editor.foreground": "#383a42",
        "editor.selectionBackground": "#dbdbdc",
        "editor.lineHighlightBackground": "#f0f0f1",
        "editorCursor.foreground": "#526fff",
        "editorLineNumber.foreground": "#9d9d9f",
        "editorLineNumber.activeForeground": "#383a42"
      },
      "tokens": [
        {
          "token": "comment",
          "foreground": "a0a1a7",
          "fontStyle": "italic"
        },
        {
          "token": "keyword",
          "foreground": "a626a4"
        },
        {
          "token": "keyword.control",
          "foreground": "a626a4"
        },
        {
          "token": "storage",
          "foreground": "a626a4"
        },
        {
          "token": "storage.type",
          "foreground": "a626a4"
        },
        {
          "token": "string",
          "foreground": "50a14f"
        },
        {
          "token": "constant.numeric",
          "foreground": "986801"
        },
        {
          "token": "constant.language",
          "foreground": "986801"
        },
        {
          "token": "constant",
          "foreground": "0184bc"
        },
        {
          "token": "variable",
          "foreground": "e45649"
        },
        {
          "token": "variable.parameter",
          "foreground": "383a42"
        },
        {
          "token": "type",
          "foreground": "c18401"
        },
        {
          "token": "entity.name.type",
          "foreground": "c18401"
        },
        {
          "token": "entity.name.class",
          "foreground": "c18401"
        },
        {
          "token": "entity.name.function",
          "foreground": "4078f2"
        },
        {
          "token": "support.function",
          "foreground": "4078f2"
        },
        {
          "token": "entity.name.tag",
          "foreground": "e45649"
        },
        {
          "token": "entity.other.attribute-name",
          "foreground": "986801"
        },
        {
          "token": "operator",
          "foreground": "0184bc"
        }
      ]
    },
    "bootBackground": "#fafafa"
  }),
  makeTheme({
    "id": "intellij-light",
    "name": "IntelliJ Light",
    "group": "Light themes",
    "description": "IntelliJ IDEA’s light editor scheme.",
    "mode": "light",
    "colors": {
      "canvas": "#e8e8e8",
      "editor": "#efefef",
      "surface": "#f5f5f5",
      "raised": "#ebebeb",
      "hover": "#e4e4e4",
      "active": "#dcdcdc",
      "border": "rgba(0, 0, 0, 0.12)",
      "borderStrong": "rgba(0, 0, 0, 0.25)",
      "text": "#000000",
      "secondary": "#3d3d3d",
      "muted": "#737373",
      "accent": "#3574f0",
      "companion": "#00627a",
      "success": "#067d17",
      "warning": "#cc7832",
      "error": "#c9372c",
      "comment": "#8c8c8c",
      "keyword": "#0033b3",
      "string": "#067d17",
      "number": "#1750eb",
      "function": "#00627a",
      "type": "#00627a",
      "operator": "#3d3d3d"
    },
    "terminal": {
      "background": "#ffffff",
      "foreground": "#000000",
      "cursor": "#3574f0",
      "cursorAccent": "#ffffff",
      "selectionBackground": "#d4d4d4",
      "selectionForeground": "#000000",
      "black": "#000000",
      "red": "#c9372c",
      "green": "#067d17",
      "yellow": "#b07d00",
      "blue": "#3574f0",
      "magenta": "#7851a9",
      "cyan": "#00627a",
      "white": "#808080",
      "brightBlack": "#737373",
      "brightRed": "#e05c52",
      "brightGreen": "#1b9930",
      "brightYellow": "#cc9a1a",
      "brightBlue": "#5c8ff7",
      "brightMagenta": "#9b6abf",
      "brightCyan": "#1a87a0",
      "brightWhite": "#000000"
    },
    "editor": {
      "base": "vs",
      "colors": {
        "editor.background": "#ffffff",
        "editor.foreground": "#000000",
        "editorGutter.background": "#ffffff",
        "minimap.background": "#f5f5f5",
        "editorLineNumber.foreground": "#a7a7a7",
        "editor.lineHighlightBackground": "#f0f0f0",
        "editor.selectionBackground": "#add6ff",
        "editorCursor.foreground": "#3574f0"
      },
      "tokens": [
        {
          "token": "comment",
          "foreground": "8c8c8c",
          "fontStyle": "italic"
        },
        {
          "token": "keyword",
          "foreground": "0033b3"
        },
        {
          "token": "storage",
          "foreground": "0033b3"
        },
        {
          "token": "string",
          "foreground": "067d17"
        },
        {
          "token": "constant.numeric",
          "foreground": "1750eb"
        },
        {
          "token": "variable",
          "foreground": "000000"
        },
        {
          "token": "entity.name.function",
          "foreground": "00627a"
        },
        {
          "token": "type",
          "foreground": "00627a"
        },
        {
          "token": "entity.name.tag",
          "foreground": "0033b3"
        },
        {
          "token": "regexp",
          "foreground": "067d17"
        },
        {
          "token": "invalid",
          "foreground": "c9372c"
        }
      ]
    },
    "bootBackground": "#f2f2f2"
  }),
  makeTheme({
    "id": "visual-studio-light",
    "name": "Visual Studio Light",
    "group": "Light themes",
    "description": "Visual Studio’s light editor palette.",
    "mode": "light",
    "colors": {
      "canvas": "#ffffff",
      "editor": "#f3f3f3",
      "surface": "#ececec",
      "raised": "#e4e4e4",
      "hover": "#dddddd",
      "active": "#d4d4d4",
      "border": "#e7e7e7",
      "borderStrong": "#cecece",
      "text": "#1f1f1f",
      "secondary": "#3b3b3b",
      "muted": "#6e6e6e",
      "accent": "#005fb8",
      "companion": "#0598bc",
      "success": "#388a34",
      "warning": "#bf8803",
      "error": "#ad0707",
      "comment": "#008000",
      "keyword": "#0000ff",
      "string": "#a31515",
      "number": "#098658",
      "function": "#795e26",
      "type": "#267f99",
      "operator": "#000000"
    },
    "terminal": {
      "background": "#ffffff",
      "foreground": "#3b3b3b",
      "cursor": "#005fb8",
      "selectionBackground": "#add6ff",
      "black": "#000000",
      "red": "#cd3131",
      "green": "#00a800",
      "yellow": "#949800",
      "blue": "#0451a5",
      "magenta": "#bc05bc",
      "cyan": "#0598bc",
      "white": "#555555",
      "brightBlack": "#666666",
      "brightRed": "#cd3131",
      "brightGreen": "#14ce14",
      "brightYellow": "#b5ba00",
      "brightBlue": "#0451a5",
      "brightMagenta": "#bc05bc",
      "brightCyan": "#0598bc",
      "brightWhite": "#a5a5a5"
    },
    "editor": {
      "base": "vs",
      "colors": {
        "editor.background": "#ffffff",
        "editor.foreground": "#000000",
        "editor.selectionBackground": "#add6ff",
        "editor.lineHighlightBackground": "#f3f3f3",
        "editorCursor.foreground": "#005fb8",
        "editorLineNumber.foreground": "#6e7681",
        "editorLineNumber.activeForeground": "#1f1f1f"
      },
      "tokens": [
        {
          "token": "comment",
          "foreground": "008000",
          "fontStyle": "italic"
        },
        {
          "token": "keyword",
          "foreground": "0000ff"
        },
        {
          "token": "keyword.control",
          "foreground": "af00db"
        },
        {
          "token": "storage",
          "foreground": "0000ff"
        },
        {
          "token": "storage.type",
          "foreground": "0000ff"
        },
        {
          "token": "string",
          "foreground": "a31515"
        },
        {
          "token": "constant.numeric",
          "foreground": "098658"
        },
        {
          "token": "constant.language",
          "foreground": "0000ff"
        },
        {
          "token": "constant",
          "foreground": "0070c1"
        },
        {
          "token": "variable",
          "foreground": "001080"
        },
        {
          "token": "variable.parameter",
          "foreground": "001080"
        },
        {
          "token": "type",
          "foreground": "267f99"
        },
        {
          "token": "entity.name.type",
          "foreground": "267f99"
        },
        {
          "token": "entity.name.class",
          "foreground": "267f99"
        },
        {
          "token": "entity.name.function",
          "foreground": "795e26"
        },
        {
          "token": "support.function",
          "foreground": "795e26"
        },
        {
          "token": "entity.name.tag",
          "foreground": "800000"
        },
        {
          "token": "entity.other.attribute-name",
          "foreground": "e50000"
        },
        {
          "token": "operator",
          "foreground": "000000"
        }
      ]
    },
    "bootBackground": "#ffffff"
  }),
];

/** Exact Cate terminal/editor planes for CURSEM presets that predate the
 *  unified schema — the chrome stays CURSEM's, the ANSI palette and Monaco
 *  rules become the authentic per-theme versions. */
export const CATE_THEME_ENHANCEMENTS: Record<string, { terminal: TerminalPalette; editor: ThemeEditorDefinition }> = {
  "tokyo-night": {
    "terminal": {
      "background": "#1a1b26",
      "foreground": "#a9b1d6",
      "cursor": "#c0caf5",
      "selectionBackground": "#33467c",
      "selectionForeground": "#c0caf5",
      "black": "#15161e",
      "red": "#f7768e",
      "green": "#9ece6a",
      "yellow": "#e0af68",
      "blue": "#7aa2f7",
      "magenta": "#bb9af7",
      "cyan": "#7dcfff",
      "white": "#a9b1d6",
      "brightBlack": "#5e6997",
      "brightRed": "#f7768e",
      "brightGreen": "#9ece6a",
      "brightYellow": "#e0af68",
      "brightBlue": "#7aa2f7",
      "brightMagenta": "#bb9af7",
      "brightCyan": "#7dcfff",
      "brightWhite": "#c0caf5"
    },
    "editor": {
      "base": "vs-dark",
      "colors": {
        "editor.background": "#1a1b26",
        "editor.foreground": "#a9b1d6",
        "editorGutter.background": "#1a1b26",
        "minimap.background": "#1a1b26",
        "editorLineNumber.foreground": "#3b4261",
        "editorLineNumber.activeForeground": "#c0caf5",
        "editor.lineHighlightBackground": "#1f2233",
        "editor.lineHighlightBorder": "#00000000",
        "editor.selectionBackground": "#33467c",
        "editorCursor.foreground": "#c0caf5",
        "contrastBorder": "#00000000"
      },
      "tokens": [
        {
          "token": "comment",
          "foreground": "565f89",
          "fontStyle": "italic"
        },
        {
          "token": "keyword",
          "foreground": "bb9af7"
        },
        {
          "token": "storage",
          "foreground": "bb9af7"
        },
        {
          "token": "string",
          "foreground": "9ece6a"
        },
        {
          "token": "constant.numeric",
          "foreground": "ff9e64"
        },
        {
          "token": "constant.language",
          "foreground": "ff9e64"
        },
        {
          "token": "variable",
          "foreground": "c0caf5"
        },
        {
          "token": "variable.parameter",
          "foreground": "e0af68"
        },
        {
          "token": "entity.name.function",
          "foreground": "7aa2f7"
        },
        {
          "token": "entity.name.class",
          "foreground": "7dcfff"
        },
        {
          "token": "entity.name.type",
          "foreground": "7dcfff"
        },
        {
          "token": "entity.name.tag",
          "foreground": "f7768e"
        },
        {
          "token": "entity.other.attribute-name",
          "foreground": "7aa2f7"
        },
        {
          "token": "support.function",
          "foreground": "7aa2f7"
        },
        {
          "token": "type",
          "foreground": "7dcfff"
        },
        {
          "token": "operator",
          "foreground": "89ddff"
        },
        {
          "token": "regexp",
          "foreground": "b4f9f8"
        },
        {
          "token": "markup.heading",
          "foreground": "7aa2f7",
          "fontStyle": "bold"
        },
        {
          "token": "markup.bold",
          "fontStyle": "bold"
        },
        {
          "token": "markup.italic",
          "fontStyle": "italic"
        },
        {
          "token": "invalid",
          "foreground": "f7768e"
        }
      ]
    }
  },
  "dracula": {
    "terminal": {
      "background": "#282a36",
      "foreground": "#f8f8f2",
      "cursor": "#f8f8f0",
      "selectionBackground": "#44475a",
      "selectionForeground": "#f8f8f2",
      "black": "#21222c",
      "red": "#ff5555",
      "green": "#50fa7b",
      "yellow": "#f1fa8c",
      "blue": "#bd93f9",
      "magenta": "#ff79c6",
      "cyan": "#8be9fd",
      "white": "#f8f8f2",
      "brightBlack": "#6272a4",
      "brightRed": "#ff6e6e",
      "brightGreen": "#69ff94",
      "brightYellow": "#ffffa5",
      "brightBlue": "#d6acff",
      "brightMagenta": "#ff92df",
      "brightCyan": "#a4ffff",
      "brightWhite": "#ffffff"
    },
    "editor": {
      "base": "vs-dark",
      "colors": {
        "editor.background": "#282a36",
        "editor.foreground": "#f8f8f2",
        "editorGutter.background": "#282a36",
        "minimap.background": "#282a36",
        "editorLineNumber.foreground": "#6272a4",
        "editorLineNumber.activeForeground": "#f8f8f2",
        "editor.lineHighlightBackground": "#313442",
        "editor.lineHighlightBorder": "#00000000",
        "editor.selectionBackground": "#44475a",
        "editorCursor.foreground": "#f8f8f0",
        "contrastBorder": "#00000000"
      },
      "tokens": [
        {
          "token": "comment",
          "foreground": "6272a4",
          "fontStyle": "italic"
        },
        {
          "token": "keyword",
          "foreground": "ff79c6"
        },
        {
          "token": "storage",
          "foreground": "ff79c6"
        },
        {
          "token": "string",
          "foreground": "f1fa8c"
        },
        {
          "token": "constant.numeric",
          "foreground": "bd93f9"
        },
        {
          "token": "constant.language",
          "foreground": "bd93f9"
        },
        {
          "token": "variable",
          "foreground": "f8f8f2"
        },
        {
          "token": "variable.parameter",
          "foreground": "ffb86c"
        },
        {
          "token": "entity.name.function",
          "foreground": "50fa7b"
        },
        {
          "token": "entity.name.class",
          "foreground": "8be9fd"
        },
        {
          "token": "entity.name.type",
          "foreground": "8be9fd"
        },
        {
          "token": "entity.name.tag",
          "foreground": "ff79c6"
        },
        {
          "token": "entity.other.attribute-name",
          "foreground": "50fa7b"
        },
        {
          "token": "support.function",
          "foreground": "8be9fd"
        },
        {
          "token": "type",
          "foreground": "8be9fd"
        },
        {
          "token": "operator",
          "foreground": "ff79c6"
        },
        {
          "token": "regexp",
          "foreground": "ff5555"
        },
        {
          "token": "markup.heading",
          "foreground": "bd93f9",
          "fontStyle": "bold"
        },
        {
          "token": "markup.bold",
          "fontStyle": "bold"
        },
        {
          "token": "markup.italic",
          "fontStyle": "italic"
        },
        {
          "token": "invalid",
          "foreground": "ff5555"
        }
      ]
    }
  },
  "nord": {
    "terminal": {
      "background": "#2e3440",
      "foreground": "#d8dee9",
      "cursor": "#d8dee9",
      "selectionBackground": "#434c5e",
      "selectionForeground": "#eceff4",
      "black": "#3b4252",
      "red": "#bf616a",
      "green": "#a3be8c",
      "yellow": "#ebcb8b",
      "blue": "#81a1c1",
      "magenta": "#b48ead",
      "cyan": "#88c0d0",
      "white": "#e5e9f0",
      "brightBlack": "#75829c",
      "brightRed": "#bf616a",
      "brightGreen": "#a3be8c",
      "brightYellow": "#ebcb8b",
      "brightBlue": "#81a1c1",
      "brightMagenta": "#b48ead",
      "brightCyan": "#8fbcbb",
      "brightWhite": "#eceff4"
    },
    "editor": {
      "base": "vs-dark",
      "colors": {
        "editor.background": "#2e3440",
        "editor.foreground": "#d8dee9",
        "editorGutter.background": "#2e3440",
        "minimap.background": "#2e3440",
        "editorLineNumber.foreground": "#4c566a",
        "editorLineNumber.activeForeground": "#d8dee9",
        "editor.lineHighlightBackground": "#3b4252",
        "editor.lineHighlightBorder": "#00000000",
        "editor.selectionBackground": "#434c5e",
        "editorCursor.foreground": "#d8dee9",
        "contrastBorder": "#00000000"
      },
      "tokens": [
        {
          "token": "comment",
          "foreground": "616e88",
          "fontStyle": "italic"
        },
        {
          "token": "keyword",
          "foreground": "81a1c1"
        },
        {
          "token": "storage",
          "foreground": "81a1c1"
        },
        {
          "token": "string",
          "foreground": "a3be8c"
        },
        {
          "token": "constant.numeric",
          "foreground": "b48ead"
        },
        {
          "token": "constant.language",
          "foreground": "81a1c1"
        },
        {
          "token": "variable",
          "foreground": "d8dee9"
        },
        {
          "token": "variable.parameter",
          "foreground": "d8dee9"
        },
        {
          "token": "entity.name.function",
          "foreground": "88c0d0"
        },
        {
          "token": "entity.name.class",
          "foreground": "8fbcbb"
        },
        {
          "token": "entity.name.type",
          "foreground": "8fbcbb"
        },
        {
          "token": "entity.name.tag",
          "foreground": "81a1c1"
        },
        {
          "token": "entity.other.attribute-name",
          "foreground": "8fbcbb"
        },
        {
          "token": "support.function",
          "foreground": "88c0d0"
        },
        {
          "token": "type",
          "foreground": "8fbcbb"
        },
        {
          "token": "operator",
          "foreground": "81a1c1"
        },
        {
          "token": "regexp",
          "foreground": "ebcb8b"
        },
        {
          "token": "markup.heading",
          "foreground": "88c0d0",
          "fontStyle": "bold"
        },
        {
          "token": "markup.bold",
          "fontStyle": "bold"
        },
        {
          "token": "markup.italic",
          "fontStyle": "italic"
        },
        {
          "token": "invalid",
          "foreground": "bf616a"
        }
      ]
    }
  },
  "solarized-dark": {
    "terminal": {
      "background": "#002b36",
      "foreground": "#839496",
      "cursor": "#93a1a1",
      "selectionBackground": "#073642",
      "selectionForeground": "#93a1a1",
      "black": "#073642",
      "red": "#dc322f",
      "green": "#859900",
      "yellow": "#b58900",
      "blue": "#268bd2",
      "magenta": "#d33682",
      "cyan": "#2aa198",
      "white": "#eee8d5",
      "brightBlack": "#657b83",
      "brightRed": "#cb4b16",
      "brightGreen": "#586e75",
      "brightYellow": "#657b83",
      "brightBlue": "#839496",
      "brightMagenta": "#6c71c4",
      "brightCyan": "#93a1a1",
      "brightWhite": "#fdf6e3"
    },
    "editor": {
      "base": "vs-dark",
      "colors": {
        "editor.background": "#002b36",
        "editor.foreground": "#839496",
        "editorGutter.background": "#002b36",
        "minimap.background": "#002b36",
        "editorLineNumber.foreground": "#586e75",
        "editorLineNumber.activeForeground": "#93a1a1",
        "editor.lineHighlightBackground": "#073642",
        "editor.lineHighlightBorder": "#00000000",
        "editor.selectionBackground": "#073642",
        "editorCursor.foreground": "#93a1a1",
        "contrastBorder": "#00000000"
      },
      "tokens": [
        {
          "token": "comment",
          "foreground": "586e75",
          "fontStyle": "italic"
        },
        {
          "token": "keyword",
          "foreground": "859900"
        },
        {
          "token": "storage",
          "foreground": "859900"
        },
        {
          "token": "string",
          "foreground": "2aa198"
        },
        {
          "token": "constant.numeric",
          "foreground": "d33682"
        },
        {
          "token": "constant.language",
          "foreground": "268bd2"
        },
        {
          "token": "variable",
          "foreground": "839496"
        },
        {
          "token": "variable.parameter",
          "foreground": "839496"
        },
        {
          "token": "entity.name.function",
          "foreground": "268bd2"
        },
        {
          "token": "entity.name.class",
          "foreground": "b58900"
        },
        {
          "token": "entity.name.type",
          "foreground": "b58900"
        },
        {
          "token": "entity.name.tag",
          "foreground": "268bd2"
        },
        {
          "token": "entity.other.attribute-name",
          "foreground": "93a1a1"
        },
        {
          "token": "support.function",
          "foreground": "268bd2"
        },
        {
          "token": "type",
          "foreground": "b58900"
        },
        {
          "token": "operator",
          "foreground": "859900"
        },
        {
          "token": "regexp",
          "foreground": "dc322f"
        },
        {
          "token": "markup.heading",
          "foreground": "268bd2",
          "fontStyle": "bold"
        },
        {
          "token": "markup.bold",
          "fontStyle": "bold"
        },
        {
          "token": "markup.italic",
          "fontStyle": "italic"
        },
        {
          "token": "invalid",
          "foreground": "dc322f"
        }
      ]
    }
  },
};
